### ISSUE TITLE
What do Assistant API response's start_index and end_index mean?

### ISSUE THREAD

**Issue by vlady1998** [vlady1998/clinical-note-assitance#1]
Hi everyone,

I'm trying to understand what the start_index and end_index numbers refer to in the assistant retrieval.

I initially assumed they were character-level indices of the text file I uploaded, but they don't seem to match up.

I've also been unable to find relevant information in the documentation.

If anyone could clarify this for me, I'd greatly appreciate it.

Thank you!

**Comment by SuperGalaxy0901** [comment]
[Assistant API Annotations - #3 by TemplarRush](https://community.openai.com/t/assistant-api-annotations/730817/3) based on the answer from [@nikunj](https://community.openai.com/u/nikunj) here it looks like " They represent the start and end index of the string to be replaced (amet?6:4+source? ) in the response text generated (text.value )."

While there isn’t an official way to do this yet. the following workaround worked for my use case - # [Tip: Making Assistants API return better annotations (besides file names)](https://community.openai.com/t/tip-making-assistants-api-return-better-annotations-besides-file-names/841838)
